import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import os
from dotenv import load_dotenv
import requests
from typing import Dict, Any

# Load environment variables
load_dotenv()

# Initialize Alpha Vantage API key
ALPHA_VANTAGE_API_KEY = os.getenv('ALPHA_VANTAGE_API_KEY')

def get_daily_adjusted_data(symbol: str, start_date: datetime) -> Dict[str, Any]:
    """
    Fetch daily adjusted stock data from Alpha Vantage API.
    This includes both price and dividend data.
    
    Parameters
    ----------
    symbol : str
        Stock symbol to fetch data for
    start_date : datetime
        Start date for historical data
        
    Returns
    -------
    dict
        Dictionary containing the API response
    """
    # Alpha Vantage API endpoint for daily adjusted data
    url = f'https://www.alphavantage.co/query'
    
    # Parameters for the API call
    params = {
        'function': 'TIME_SERIES_DAILY_ADJUSTED',  # This endpoint includes dividends
        'symbol': symbol,
        'outputsize': 'full',
        'apikey': ALPHA_VANTAGE_API_KEY
    }
    
    try:
        response = requests.get(url, params=params)
        response.raise_for_status()  # Raise an exception for bad status codes
        data = response.json()
        
        # Debug: Print API response
        print(f"\nAPI Response for {symbol}:")
        print(f"Status Code: {response.status_code}")
        
        # Check for API errors
        if 'Error Message' in data:
            print(f"Error Message: {data['Error Message']}")
            raise Exception(f"Alpha Vantage API Error: {data['Error Message']}")
            
        # Check for API notes (rate limits, etc.)
        if 'Note' in data:
            print(f"API Note: {data['Note']}")
            
        # Check for missing data
        if 'Time Series (Daily)' not in data:
            print("No time series data found in response")
            print("Available keys:", list(data.keys()))
            if 'Information' in data:
                print(f"API Information: {data['Information']}")
            raise Exception(f"No time series data available for {symbol}")
            
        return data
    except requests.exceptions.RequestException as e:
        print(f"Network error fetching data for {symbol}: {str(e)}")
        return None
    except Exception as e:
        print(f"Error fetching data for {symbol}: {str(e)}")
        return None

def merge_pricedata(portfolio, index):
    """
    Reads portfolio dataframe generated by get_userdata(), and extracts a list of stock tickers in
    the portfolio. Uses Alpha Vantage API to get time series stock price data for the stocks listed and 
    merge price data with the portfolio dataframe. The returned dataframe is indexed as a time series, 
    with business day frequency.

    Parameters
    ----------
    portfolio : pandas.DataFrame
        portfolio dataframe generated by get_userdata().
    index : string
        stock ticker to compare portfolio performance. Typically this would be the ticker
        of an ETF that tracks an index, eg "SPY" which tracks the S&P 500 index.

    Returns
    -------
    import_a : pandas.DataFrame
        Time series dataframe containing stock purchase and sale information, merged with stock
        price data over the time frame convered by the portfolio
    """
    # Portfolio start and end time for extracting data using API
    start_date = min(portfolio.index)
    
    # Fetch stock prices using API and merge with trading data
    print("\nAPI call in progress...\n")

    # Extract list of portfolio tickers
    tickers = list(portfolio.columns.levels[1]) + [index]
    for i in tickers:
        try:
            # Get daily adjusted data from Alpha Vantage (includes dividends)
            data = get_daily_adjusted_data(i, start_date)
            
            if data and 'Time Series (Daily)' in data:
                # Convert to DataFrame
                df = pd.DataFrame.from_dict(data['Time Series (Daily)'], orient='index')
                df.index = pd.to_datetime(df.index)
                df = df.sort_index()
                
                # Rename columns to match expected format
                df = df.rename(columns={
                    '4. close': 'Close',
                    '7. dividend amount': 'Dividends'
                })
                
                # Filter data from start_date onwards
                df = df[df.index >= start_date]
                
                if df.empty:
                    print(f"Warning: No data available for {i} after {start_date}. Skipping...")
                    continue
                
                # Create MultiIndex columns
                cols = pd.MultiIndex.from_arrays(
                    [["$", "Div"], [i, i]], names=["Params", "Company"]
                )
                
                # Select only Close and Dividends columns
                df = df[['Close', 'Dividends']]
                df.columns = cols
                
                # Merge portfolio and prices dataframes
                portfolio = pd.merge(
                    portfolio, df, how="outer", left_index=True, right_index=True
                ).drop_duplicates()
                
                print(f"Successfully fetched data for {i}")
            else:
                print(f"Error: No data available for stock ticker {i}. Skipping...")
                
        except Exception as e:
            print(f"Error processing data for {i}: {str(e)}")
            continue

    print("API call complete\n")

    # Set to 'Business day' datetime frequency
    portfolio = portfolio.sort_index().asfreq(freq="B")

    return portfolio 