import os
try:
    from dotenv import load_dotenv
except ModuleNotFoundError:
    def load_dotenv():
        return None
import share_tracking as share
import alpha_vantage_tracking as av
import finnhub_tracking as fh

# Load environment variables
load_dotenv()

# Default data provider
DEFAULT_PROVIDER = 'yfinance'

def get_data_provider():
    """
    Get the current data provider from environment variable.
    Returns 'yfinance' if not set.
    """
    provider = os.getenv('DATA_PROVIDER', DEFAULT_PROVIDER)
    if not provider:
        return DEFAULT_PROVIDER
    provider = provider.strip().lower()
    if provider not in ['yfinance', 'alpha_vantage', 'finnhub']:
        return DEFAULT_PROVIDER
    return provider

def set_data_provider(provider: str):
    """
    Set the data provider in environment variable.
    
    Parameters
    ----------
    provider : str
        Data provider to use ('yfinance', 'alpha_vantage', or 'finnhub')
    """
    if provider not in ['yfinance', 'alpha_vantage', 'finnhub']:
        raise ValueError(f"Unknown data provider: {provider}")
    
    # Update .env file
    env_path = os.path.join(os.getcwd(), '.env')
    
    # Read existing .env file
    if os.path.exists(env_path):
        with open(env_path, 'r') as f:
            lines = f.readlines()
        
        # Update or add DATA_PROVIDER line
        provider_line = f"DATA_PROVIDER={provider}\n"
        found = False
        for i, line in enumerate(lines):
            if line.startswith('DATA_PROVIDER='):
                lines[i] = provider_line
                found = True
                break
        
        if not found:
            lines.append(provider_line)
        
        # Write back to .env file
        with open(env_path, 'w') as f:
            f.writelines(lines)
    else:
        # Create new .env file
        with open(env_path, 'w') as f:
            f.write(f"DATA_PROVIDER={provider}\n")

def merge_pricedata(portfolio, index):
    """
    Get stock data using the configured data provider.
    
    Parameters
    ----------
    portfolio : pandas.DataFrame
        portfolio dataframe generated by get_userdata().
    index : string
        stock ticker to compare portfolio performance.
        
    Returns
    -------
    pandas.DataFrame
        Time series dataframe containing stock purchase and sale information
    """
    provider = get_data_provider()
    
    if provider == 'yfinance':
        return share.merge_pricedata(portfolio, index)
    elif provider == 'alpha_vantage':
        return av.merge_pricedata(portfolio, index)
    elif provider == 'finnhub':
        return fh.merge_pricedata(portfolio, index)
    else:
        raise ValueError(f"Unknown data provider: {provider}") 
