import pandas as pd
import numpy as np
import finnhub
from datetime import datetime, timedelta
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Initialize Finnhub client
finnhub_client = finnhub.Client(api_key=os.getenv('FINNHUB_API_KEY'))

def merge_pricedata(portfolio, index):
    """
    Reads portfolio dataframe generated by get_userdata(), and extracts a list of stock tickers in
    the portfolio. Uses Finnhub API to get time series stock price data for the stocks listed and 
    merge price data with the portfolio dataframe. The returned dataframe is indexed as a time series, 
    with business day frequency.

    Parameters
    ----------
    portfolio : pandas.DataFrame
        portfolio dataframe generated by get_userdata().
    index : string
        stock ticker to compare portfolio performance. Typically this would be the ticker
        of an ETF that tracks an index, eg "SPY" which tracks the S&P 500 index.

    Returns
    -------
    import_a : pandas.DataFrame
        Time series dataframe containing stock purchase and sale information, merged with stock
        price data over the time frame convered by the portfolio
    """

    # Portfolio start and end time for extracting data using API
    start_date = min(portfolio.index)
    end_date = datetime.now()
    
    # Convert dates to Unix timestamps for Finnhub API
    start_timestamp = int(start_date.timestamp())
    end_timestamp = int(end_date.timestamp())

    # Fetch stock prices using API and merge with trading data
    inputdata = {}
    print("\nAPI call in progress...\n")

    # Extract list of portfolio tickers
    tickers = list(portfolio.columns.levels[1]) + [index]
    for i in tickers:
        try:
            # Get daily candle data from Finnhub
            candle_data = finnhub_client.stock_candles(i, 'D', start_timestamp, end_timestamp)
            
            if candle_data['s'] == 'ok':
                # Convert to DataFrame
                df = pd.DataFrame({
                    'Close': candle_data['c'],
                    'Dividends': [0] * len(candle_data['c'])  # Finnhub doesn't provide dividend data
                }, index=pd.to_datetime(candle_data['t'], unit='s'))
                
                # Create MultiIndex columns
                cols = pd.MultiIndex.from_arrays(
                    [["$", "Div"], [i, i]], names=["Params", "Company"]
                )
                
                df.columns = cols
                
                # Merge portfolio and prices dataframes
                portfolio = pd.merge(
                    portfolio, df, how="outer", left_index=True, right_index=True
                ).drop_duplicates()
            else:
                print(f"Error: No data available for stock ticker {i}. Skipping...")
                
        except Exception as e:
            print(f"Error fetching data for {i}: {str(e)}")
            continue

    print("API call complete\n")

    # Set to 'Business day' datetime frequency
    portfolio = portfolio.sort_index().asfreq(freq="B")

    return portfolio 